import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Card } from '../ui';
import type { ReportData } from '../../types/reportTypes'; // Only need ReportData for aiUxDesignSuggestions
import { unwrapMarkdown } from '../../utils/textUtils';

interface AiUxDesignSectionProps {
  aiUxDesignSuggestions?: ReportData['aiUxDesignSuggestions'];
  // reportStatus: ReportData['status']; // Overall report status might not be needed if aiUxDesignSuggestions has its own status
}

const AiUxDesignSection: React.FC<AiUxDesignSectionProps> = ({ aiUxDesignSuggestions }) => {
  if (!aiUxDesignSuggestions || aiUxDesignSuggestions.status === 'pending' || aiUxDesignSuggestions.status === 'processing') {
    return (
      <Card title="AI UX & Design Insights">
        <p className="text-slate-500">AI-powered UX and design suggestions are being generated...</p>
      </Card>
    );
  }

  if (aiUxDesignSuggestions.status === 'skipped') {
    return (
      <Card title="AI UX & Design Insights">
        <p className="text-slate-500">AI UX & Design suggestions were skipped. {aiUxDesignSuggestions.error ? `Reason: ${aiUxDesignSuggestions.error}` : ''}</p>
      </Card>
    );
  }

  if (aiUxDesignSuggestions.status === 'error') {
    return (
      <Card title="AI UX & Design Insights">
        <p className="text-red-500">Error loading AI UX & Design suggestions: {aiUxDesignSuggestions.error}</p>
      </Card>
    );
  }

  if (!aiUxDesignSuggestions.suggestions || aiUxDesignSuggestions.suggestions.length === 0) {
    return (
      <Card title="AI UX & Design Insights">
        <p className="text-slate-500">No AI-powered UX or design suggestions available for this report.</p>
      </Card>
    );
  }

  // If we reach here, aiUxDesignSuggestions.status must be 'completed'
  // and aiUxDesignSuggestions.suggestions is guaranteed to exist and not be empty.
  return (
    <Card title="AI UX & Design Insights" className="font-sans">
      {aiUxDesignSuggestions.modelUsed && (
        <p className="text-xs text-slate-500 mb-3">Insights generated by: {aiUxDesignSuggestions.modelUsed}</p>
      )}
      <ul className="space-y-4 list-none p-0">
        {aiUxDesignSuggestions.suggestions.map((item, index) => (
          <li key={index} className="p-4 bg-slate-50 rounded-md shadow-sm border border-slate-200">
            {item.screenContext && (
              <p className="text-xs text-sky-700 font-medium mb-1 capitalize">
                Context: {item.screenContext}
              </p>
            )}
            <div className="prose prose-sm max-w-none text-slate-800 prose-p:font-medium prose-p:mb-1.5 prose-p:leading-snug">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>{unwrapMarkdown(item.suggestion)}</ReactMarkdown> 
            </div>
            {item.reasoning && (
              <div className="prose prose-xs max-w-none text-slate-600 pl-1 border-l-2 border-slate-300 italic prose-p:italic prose-strong:font-semibold prose-strong:not-italic">
                <strong>Reasoning:</strong> <ReactMarkdown remarkPlugins={[remarkGfm]}>{unwrapMarkdown(item.reasoning)}</ReactMarkdown> 
              </div>
            )}
          </li>
        ))}
      </ul>
    </Card>
  );
};

export default AiUxDesignSection;
