import React from 'react';
import { Card } from '../ui';
import type { ReportData } from '../../types/report'; // Only need ReportData for aiUxDesignSuggestions

interface AiUxDesignSectionProps {
  aiUxDesignSuggestions: ReportData['aiUxDesignSuggestions'];
  // reportStatus: ReportData['status']; // Overall report status might not be needed if aiUxDesignSuggestions has its own status
}

const AiUxDesignSection: React.FC<AiUxDesignSectionProps> = ({ aiUxDesignSuggestions }) => {
  return (
    <Card title="AI UX & Design Insights" className="font-sans">
      {!aiUxDesignSuggestions || aiUxDesignSuggestions.status === 'pending' ? (
        <p className="text-slate-600">
          AI-powered UX & Design suggestions are being generated or will appear here once the analysis is complete.
        </p>
      ) : aiUxDesignSuggestions.status === 'skipped' ? (
        <p className="text-slate-600">
          AI UX & Design analysis was skipped. {aiUxDesignSuggestions.error ? `Reason: ${aiUxDesignSuggestions.error}` : ''}
        </p>
      ) : aiUxDesignSuggestions.status === 'error' ? (
        <p className="text-red-600">
          Error during AI UX & Design analysis: {aiUxDesignSuggestions.error || 'An unspecified error occurred.'}
        </p>
      ) : aiUxDesignSuggestions.status === 'completed' && aiUxDesignSuggestions.suggestions && aiUxDesignSuggestions.suggestions.length > 0 ? (
        <>
          {aiUxDesignSuggestions.modelUsed && (
            <p className="text-xs text-slate-500 mb-3">Insights generated by: {aiUxDesignSuggestions.modelUsed}</p>
          )}
          <ul className="space-y-4 list-none p-0">
            {aiUxDesignSuggestions.suggestions.map((item, index) => (
              <li key={index} className="p-4 bg-slate-50 rounded-md shadow-sm border border-slate-200">
                {item.screenContext && (
                  <p className="text-xs text-sky-700 font-medium mb-1 capitalize">
                    Context: {item.screenContext}
                  </p>
                )}
                <p className="text-sm text-slate-800 font-medium mb-1.5 leading-snug">{item.suggestion}</p>
                {item.reasoning && (
                  <p className="text-xs text-slate-600 pl-1 border-l-2 border-slate-300 italic">
                    <span className="font-semibold not-italic">Reasoning:</span> {item.reasoning}
                  </p>
                )}
              </li>
            ))}
          </ul>
        </>
      ) : aiUxDesignSuggestions.status === 'completed' ? (
          <p className="text-slate-600">
            AI analysis completed, but no specific suggestions were provided.
          </p>
      ) : (
        <p className="text-slate-600">
          The status of AI UX & Design suggestions is unknown.
        </p>
      )}
    </Card>
  );
};

export default AiUxDesignSection;
