import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Card } from '../ui';
import type { ReportData } from '../../types/report'; // Only need ReportData for llmReportSummary
import { unwrapMarkdown } from '../../utils/textUtils';
import { getProviderLabel } from '../../config/aiProviders';

interface LlmSummarySectionProps {
  llmReportSummary: ReportData['llmReportSummary'];
  // reportStatus: ReportData['status']; // Overall report status might not be needed
}

const LlmSummarySection: React.FC<LlmSummarySectionProps> = ({ llmReportSummary }) => {
  const providerLabel = llmReportSummary?.providerUsed
    ? getProviderLabel(llmReportSummary.providerUsed) ?? llmReportSummary.providerUsed
    : undefined;
  const modelLabel = llmReportSummary?.modelUsed;
  const attribution = providerLabel && modelLabel
    ? `${providerLabel} – ${modelLabel}`
    : providerLabel ?? modelLabel;

  return (
    <Card title="AI-Generated Overview" className="font-sans">
      {!llmReportSummary || llmReportSummary.status === 'pending' ? (
        <p className="text-slate-600">
          The AI-generated overview is being prepared or will appear here once available.
        </p>
      ) : llmReportSummary.status === 'skipped' ? (
        <p className="text-slate-600">
          AI-Generated Overview was skipped. {llmReportSummary.error ? `Reason: ${llmReportSummary.error}` : ''}
        </p>
      ) : llmReportSummary.status === 'error' ? (
        <p className="text-red-600">
          Error generating AI Overview: {llmReportSummary.error || 'An unspecified error occurred.'}
        </p>
      ) : llmReportSummary.status === 'completed' && llmReportSummary.summaryText ? (
        <>
          {attribution && (
            <p className="text-xs sm:text-sm text-slate-500 mb-2 sm:mb-3">
              Summary generated by: {attribution}
            </p>
          )}
          <div className="prose prose-sm sm:prose-base max-w-none text-slate-700">
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              components={{
                h3: ({ node, ...props }) => (
                  <h3 className="text-base sm:text-lg font-semibold mt-3 sm:mt-4 mb-1.5 sm:mb-2 text-slate-800" {...props} />
                ),
                p: ({ node, ...props }) => (
                  <p className="mb-2 leading-relaxed text-slate-700" {...props} />
                ),
                ul: ({ node, ...props }) => (
                  <ul className="list-disc pl-5 mb-2 space-y-1" {...props} />
                ),
                li: ({ node, ...props }) => (
                  <li className="text-slate-700" {...props} />
                ),
                a: ({ node, ...props }) => (
                  <a className="text-blue-600 hover:text-blue-700 hover:underline" {...props} />
                ),
                strong: ({ node, ...props }) => (
                  <strong className="font-semibold text-slate-800" {...props} />
                ),
              }}
            >
              {unwrapMarkdown(llmReportSummary.summaryText)}
            </ReactMarkdown>
          </div>
        </>
      ) : llmReportSummary.status === 'completed' ? (
          <p className="text-slate-600">
            AI Overview analysis completed, but no summary text was provided.
          </p>
      ) : (
        <p className="text-slate-600">
          The status of the AI-Generated Overview is unknown.
        </p>
      )}
    </Card>
  );
};

export default LlmSummarySection;
