import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Card } from '../ui';
import type { ReportData } from '../../types/report'; // Only need ReportData for llmReportSummary

interface LlmSummarySectionProps {
  llmReportSummary: ReportData['llmReportSummary'];
  // reportStatus: ReportData['status']; // Overall report status might not be needed
}

const LlmSummarySection: React.FC<LlmSummarySectionProps> = ({ llmReportSummary }) => {
  return (
    <Card title="AI-Generated Overview" className="font-sans">
      {!llmReportSummary || llmReportSummary.status === 'pending' ? (
        <p className="text-slate-600">
          The AI-generated overview is being prepared or will appear here once available.
        </p>
      ) : llmReportSummary.status === 'skipped' ? (
        <p className="text-slate-600">
          AI-Generated Overview was skipped. {llmReportSummary.error ? `Reason: ${llmReportSummary.error}` : ''}
        </p>
      ) : llmReportSummary.status === 'error' ? (
        <p className="text-red-600">
          Error generating AI Overview: {llmReportSummary.error || 'An unspecified error occurred.'}
        </p>
      ) : llmReportSummary.status === 'completed' && llmReportSummary.summaryText ? (
        <>
          {llmReportSummary.modelUsed && (
            <p className="text-xs text-slate-500 mb-3">Summary generated by: {llmReportSummary.modelUsed}</p>
          )}
          <div className="prose prose-sm max-w-none text-slate-700">
            {(() => {
              const rawText = llmReportSummary.summaryText;
              let markdownContent = "";
              const parts = rawText.split(/\n\s*`{3}(?:markdown|\w+)?\n/);
              if (parts.length > 1) {
                let mainMarkdownSection = parts.slice(1).join('\n```markdown\n');
                mainMarkdownSection = mainMarkdownSection.replace(/\n\s*`{3}\s*$/, '').trim();
                markdownContent = mainMarkdownSection;
              } else {
                markdownContent = rawText.replace(/^(\s*`{3}(markdown|\w+)?\n)?([\s\S]+?)(\n\s*`{3}\s*)?$/, '$3').trim();
              }
              return (
                  <ReactMarkdown
                    remarkPlugins={[remarkGfm]}
                    components={{
                      h3: ({node, ...props}) => <h3 className="text-lg font-semibold mt-4 mb-2 text-slate-800" {...props} />,
                      p: ({node, ...props}) => <p className="mb-2 leading-relaxed text-slate-700" {...props} />,
                      ul: ({node, ...props}) => <ul className="list-disc pl-5 mb-2 space-y-1" {...props} />,
                      li: ({node, ...props}) => <li className="text-slate-700" {...props} />,
                      a: ({node, ...props}) => <a className="text-blue-600 hover:text-blue-700 hover:underline" {...props} />,
                      strong: ({node, ...props}) => <strong className="font-semibold text-slate-800" {...props} />,
                    }}
                  >
                    {markdownContent}
                  </ReactMarkdown>
              );
            })()}
          </div>
        </>
      ) : llmReportSummary.status === 'completed' ? (
          <p className="text-slate-600">
            AI Overview analysis completed, but no summary text was provided.
          </p>
      ) : (
        <p className="text-slate-600">
          The status of the AI-Generated Overview is unknown.
        </p>
      )}
    </Card>
  );
};

export default LlmSummarySection;
